// 画像・モデル交換時に file:// 用データを更新。build.cjs からも自動実行。
const fs=require('fs'),path=require('path');
const assets=path.join(__dirname,'assets'),screens=path.join(assets,'screenshots'),data={};
for(const name of fs.readdirSync(screens).sort()){
  const ext=path.extname(name).toLowerCase();
  const mime={'.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp'}[ext];
  if(mime)data['assets/screenshots/'+name]='data:'+mime+';base64,'+fs.readFileSync(path.join(screens,name)).toString('base64');
}
fs.writeFileSync(path.join(assets,'screenshots-data.js'),'/* Generated by update-assets.cjs for offline file:// textures. */\nwindow.PORTFOLIO_SCREENSHOTS='+JSON.stringify(data)+';\n');
fs.writeFileSync(path.join(assets,'hamster-data.js'),'window.HAMSTER_GLB='+JSON.stringify(fs.readFileSync(path.join(assets,'hamster.glb')).toString('base64'))+';\n');
console.log('Offline images and hamster data updated.');
